### ISSUE TITLE
Install fail (variant decomposition test)

### ISSUE THREAD

**Issue by davemcg** [Illumina/hap.py#15] opened 2017-04-18 17:03 UTC
```
Chr prefixed truth test successful
Chr prefix detection tests SUCCEEDED!
2017-04-18 13:00:40,482 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-18 13:00:40,483 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
Variant decomposition test Hap.py v0.3.7 from /home/mcgaugheyd/hap.py-install/bin
2017-04-18 13:00:41,274 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-18 13:00:41,275 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-18 13:00:41,518 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-18 13:00:41,519 ERROR    coercing to Unicode: need string or buffer, NoneType found
2017-04-18 13:00:41,519 ERROR    Traceback (most recent call last):
2017-04-18 13:00:41,519 ERROR      File "/home/mcgaugheyd/hap.py-install/bin/hap.py", line 460, in <module>
2017-04-18 13:00:41,519 ERROR        main()
2017-04-18 13:00:41,519 ERROR      File "/home/mcgaugheyd/hap.py-install/bin/hap.py", line 199, in main
2017-04-18 13:00:41,519 ERROR        if not os.path.exists(args.ref):
2017-04-18 13:00:41,519 ERROR      File "/home/mcgaugheyd/anaconda2/lib/python2.7/genericpath.py", line 26, in exists
2017-04-18 13:00:41,519 ERROR        os.stat(path)
2017-04-18 13:00:41,520 ERROR    TypeError: coercing to Unicode: need string or buffer, NoneType found
hap.py failed!
Variant decomposition test FAILED!
Traceback (most recent call last):
  File "install.py", line 334, in <module>
    main()
  File "install.py", line 330, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 199, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/home/mcgaugheyd/anaconda2/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/mcgaugheyd/hap.py-install && /usr/local/bin/hap.py/src/sh/run_tests.sh' returned non-zero exit status 1
```

**Comment by pkrusche** [comment] 2017-04-20 10:37
Hi, I think this is caused by hap.py not finding a reference Fasta file (see https://github.com/Illumina/hap.py/issues/13#issuecomment-286668163 ) -- making this explicit in the installer is on the backlog for the next version. 

Until then, you can supply a location before running the installer:

```
export HG19=<path-to-hg19.fa>
python install.py ...
```

(see also the last two lines in the Dockerfile in  https://github.com/Illumina/hap.py/issues/13#issuecomment-286375551 )

**Comment by pkrusche** [comment] 2017-04-24 15:11
Closing -- please reopen if this is still an issue.

**Closed by pkrusche** 2017-04-24 15:11 UTC

**Comment by davemcg** [comment] 2017-04-26 13:35
```
$ export HG19=/home/Genomic_Files/hg19/ucsc.hg19.fasta
```

```
Chr prefixed truth test successful
Chr prefix detection tests SUCCEEDED!
2017-04-26 09:32:11,703 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-26 09:32:11,704 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
Variant decomposition test Hap.py v0.3.7 from /home/mcgaugheyd/hap.py-install/bin
2017-04-26 09:32:12,258 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-26 09:32:12,260 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-26 09:32:12,486 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2017-04-26 09:32:12,486 ERROR    coercing to Unicode: need string or buffer, NoneType found
2017-04-26 09:32:12,486 ERROR    Traceback (most recent call last):
2017-04-26 09:32:12,486 ERROR      File "/home/mcgaugheyd/hap.py-install/bin/hap.py", line 460, in <module>
2017-04-26 09:32:12,486 ERROR        main()
2017-04-26 09:32:12,486 ERROR      File "/home/mcgaugheyd/hap.py-install/bin/hap.py", line 199, in main
2017-04-26 09:32:12,486 ERROR        if not os.path.exists(args.ref):
2017-04-26 09:32:12,487 ERROR      File "/usr/lib/python2.7/genericpath.py", line 26, in exists
2017-04-26 09:32:12,487 ERROR        os.stat(path)
2017-04-26 09:32:12,487 ERROR    TypeError: coercing to Unicode: need string or buffer, NoneType found
hap.py failed!
Variant decomposition test FAILED!
Traceback (most recent call last):
  File "install.py", line 334, in <module>
    main()
  File "install.py", line 330, in main
    test_haplotypes(source_dir, python_shebang, args)
  File "install.py", line 199, in test_haplotypes
    subprocess.check_call(to_run, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
```

```
$ echo $HG19
/home/Genomic_Files/hg19/ucsc.hg19.fasta
```

I'll just try the docker image.

**Comment by pkrusche** [comment] 2017-04-26 13:41
I have just uploaded an updated image (see #16).

Another thing to try could be to set 

```
export HGREF=/home/Genomic_Files/hg19/ucsc.hg19.fasta
...
```

The next release of hap.py will have an installer option for specifying the default location of a hg19 reference.
